### ISSUE TITLE
[github.com] bad rule "s3.amazonaws.com"

### ISSUE THREAD

**Issue by KOSHACHIJ** [curbengh/phishing-filter#1]
Downloading releases and attaching files is blocked.

![2020-10-14_210104](https://user-images.githubusercontent.com/67644959/96027598-c3d38280-0e60-11eb-8167-c3c89716ef1f.png)
![2020-10-14_205852](https://user-images.githubusercontent.com/67644959/96027600-c7ffa000-0e60-11eb-865a-c62556f11d67.png)

**Comment by curbengh** [comment]
Added to exclusion list. https://gitlab.com/curben/phishing-filter/-/issues/3

The rule has already been removed in today's scheduled update, before the commit. If the issue persists, suggest to force update the filter lists.
