### ISSUE TITLE
pomoc.o2.pl

### ISSUE THREAD

**Issue by AroKol78** [curbengh/phishing-filter#2]
Phishing URL Blocklist (use `https://curben.gitlab.io/phishing-filter-mirror/phishing-filter.txt`)
`https://pomoc.o2.pl/` blocked by `||pomoc.o2.pl^`
`pomoc.o2.pl` is help for handling my mail

**Comment by krystian3w** [comment]
https://github.com/curbengh/phishing-filter/blob/c518b2dff612f367c56f9462084b9a9af4a90260/dist/phishing-filter.txt#L5490 - so old.

**Comment by curbengh** [comment]
99ca30b7deacbf18c329c373a429f364b2ee73b5

**Comment by krystian3w** [comment]
PhisTank disabled vote and detect url as offline so gone form project files - both how long ago and when back?
