### ISSUE TITLE
s3.dualstack.us-east-1.amazonaws.com [Incorrect blocking]

### ISSUE THREAD

**Issue by Alex-302** [curbengh/phishing-filter#4]
Original report: https://github.com/AdguardTeam/AdguardFilters/issues/162573

> Username: @Jamyn
> Within AdGuard Home, the "Phishing URL Blocklist (PhishTank and OpenPhish)" blocks s3.dualstack.us-east-1.amazonaws.com. Steam (a gaming platform) uses the subdomain steamcloud-us-east.s3.dualstack.us-east-1.amazonaws.com to save game state, so blocking this URL means some game saves can "randomly" fail if Steam selects the us-east region for the save.  Users will see a generic "cloud sync error" in the Steam client.

Can't find a source of the blocking rule.

**Comment by curbengh** [comment]
fixed by ecd739a846a7074ec35a1288d9b341f7731241b7
